# Generated by Django 5.1.5 on 2025-02-14 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_id_vendor'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.systemcategory'),
        ),
    ]
