# Generated by Django 5.1.5 on 2025-04-19 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode_of_transport', models.CharField(choices=[('bicycle', 'Bicycle'), ('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck')], max_length=50)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='inactive', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('drivers_license_front', models.ImageField(blank=True, help_text='An image of the drivers license front.', null=True, upload_to='verification/')),
                ('drivers_license_back', models.ImageField(blank=True, help_text="An image of the driver's license back.", null=True, upload_to='verification/')),
                ('vehicle_insurance', models.ImageField(blank=True, help_text="An image of the vehicle's insurance.", null=True, upload_to='verification/')),
                ('vehicle_registration', models.ImageField(blank=True, help_text="An image of the vehicle's registration certificate.", null=True, upload_to='verification/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
