# Generated by Django 5.1.5 on 2025-04-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
