# Generated by Django 5.1.5 on 2025-04-28 17:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_vendor_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_images'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='drivers_license_back',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="An image of the driver's license back.", max_length=255, null=True, verbose_name='verification'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='drivers_license_front',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="An image of the driver's license front.", max_length=255, null=True, verbose_name='verification'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='vehicle_insurance',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="An image of the vehicle's insurance.", max_length=255, null=True, verbose_name='verification'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='vehicle_registration',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="An image of the vehicle's registration certificate.", max_length=255, null=True, verbose_name='verification'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='vendor_images'),
        ),
    ]
