# Generated by Django 5.1.5 on 2025-02-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='close_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='close_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='open_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='open_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
