# Generated by Django 5.1.5 on 2025-05-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_vendor_city_vendor_country_vendor_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Whether the rider is currently online and available'),
        ),
        migrations.AddField(
            model_name='rider',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
