# Generated by Django 5.1.5 on 2025-05-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_address_location_latitude_address_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='location_latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='location_longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='location_latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='location_longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
