# Generated by Django 5.1.5 on 2025-04-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_verificationcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('buyer', 'buyer'), ('vendor', 'vendor'), ('rider', 'rider')], default='buyer', max_length=10),
        ),
    ]
