# Generated by Django 5.1.5 on 2025-05-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_riderrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_verification', 'pending_verification')], default='inactive', max_length=50),
        ),
    ]
