# Generated by Django 5.1.5 on 2025-06-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_rider_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='document_status',
            field=models.CharField(choices=[('pending', 'apprpendingoved'), ('approved', 'approved'), ('submiited', 'submiited'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='rider',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_verification', 'pending_verification'), ('document_rejected', 'Document rejected')], default='inactive', max_length=50),
        ),
    ]
