# Generated by Django 5.1.5 on 2025-07-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rider_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='balance',
        ),
    ]
