# Generated by Django 5.1.5 on 2025-07-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_alter_notification_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bank_account",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="bank_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
