# Generated by Django 5.1.5 on 2025-09-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_vendorissuereporting"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="is_marketplace",
            field=models.BooleanField(default=False),
        ),
    ]
