# Generated by Django 5.1.5 on 2025-09-24 12:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_vendor_is_marketplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="nin_back",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="An image of the NIN back.",
                max_length=255,
                null=True,
                verbose_name="verification",
            ),
        ),
        migrations.AddField(
            model_name="rider",
            name="nin_front",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="An image of the NIN front.",
                max_length=255,
                null=True,
                verbose_name="verification",
            ),
        ),
    ]
