# Generated by Django 5.1.5 on 2025-09-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0022_rider_nin_back_rider_nin_front"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="rider",
            name="location_latitude",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="rider",
            name="location_longitude",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
