# Generated by Django 5.1.5 on 2025-09-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0023_rider_address_rider_location_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="city",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="rider",
            name="country",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="rider",
            name="state",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
