# Generated by Django 5.1.5 on 2025-09-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0024_rider_city_rider_country_rider_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
