# Generated by Django 5.1.5 on 2025-10-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0025_user_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_image",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
