# Generated by Django 5.1.5 on 2025-10-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0026_remove_user_profile_image_user_profile_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="vendor",
            name="logo_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="thumbnail_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
