# Generated by Django 5.1.5 on 2025-10-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0027_remove_vendor_logo_remove_vendor_thumbnail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="delivery_radius_km",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
