# Generated by Django 5.1.5 on 2025-10-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0028_vendor_delivery_radius_km"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="verificationcode",
            name="verification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email Verification"),
                    ("phone", "Phone Verification"),
                    ("password", "Password Reset"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
