# Generated by Django 5.1.5 on 2025-10-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0029_vendor_is_approved_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="vendor",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
