# Generated by Django 5.1.5 on 2025-10-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0030_remove_vendor_is_approved_vendor_approval_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="approval_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
