# Generated by Django 5.1.5 on 2025-10-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0031_vendor_approval_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.CharField(
                blank=True,
                help_text="Date of birth in MM-DD format (e.g., 03-15)",
                max_length=5,
                null=True,
            ),
        ),
    ]
