# Generated by Django 5.1.5 on 2025-11-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0032_rename_date_of_birth_to_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="delivery_radius_km",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
