# Generated by Django 5.1.5 on 2025-11-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0033_alter_vendor_delivery_radius_km"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rider",
            name="document_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("submiited", "submiited"),
                    ("rejected", "rejected"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="rider",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("suspended", "Suspended"),
                ],
                default="inactive",
                max_length=50,
            ),
        ),
    ]
