# Generated by Django 5.1.5 on 2026-01-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0034_alter_rider_document_status_alter_rider_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rider",
            name="document_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("submitted", "submitted"),
                    ("rejected", "rejected"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
