# Generated by Django 5.1.5 on 2026-01-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0035_alter_rider_document_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="commission_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Custom commission rate for this vendor. Leave blank to use category or platform default.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
