# Generated by Django 5.1.5 on 2026-01-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0036_vendor_commission_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="delivery_percentage_off",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Delivery discount for this user (%)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
