# Generated by Django 5.1.5 on 2026-02-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0038_rider_next_of_kin_rider_next_of_kin_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcode",
            name="code",
            field=models.CharField(max_length=6),
        ),
    ]
