# Generated by Django 5.1.5 on 2026-02-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0039_alter_verificationcode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rider",
            name="current_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=19, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rider",
            name="current_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=19, null=True
            ),
        ),
    ]
