# Generated by Django 5.1.5 on 2026-03-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0040_alter_rider_current_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="average_customer_rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="rider",
            name="is_in_house_rider",
            field=models.BooleanField(
                default=False,
                help_text="Marketplace riders are in-house and receive a fixed salary",
            ),
        ),
        migrations.AddField(
            model_name="rider",
            name="on_time_delivery_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="rider",
            name="order_acceptance_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="rider",
            name="salary",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Monthly salary for in-house riders",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="rider",
            name="successful_delivery_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
