# Generated by Django 5.1.5 on 2026-04-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0043_auto_20260331_1725"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="close_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="open_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
