# Generated by Django 5.1.5 on 2026-04-27 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_vendor_marketplace_delivery_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorissuereporting',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='StaffPagePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.CharField(choices=[('overview', 'Overview'), ('orders', 'Order Management'), ('vendor', 'Vendor Management'), ('riders', 'Rider Management'), ('rider-verification', 'Rider Verification'), ('customer', 'Customer Management'), ('insights', 'Insights'), ('marketplace', 'Marketplace Management'), ('transactions', 'Transactions')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='page_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Page Permission',
                'verbose_name_plural': 'Staff Page Permissions',
                'ordering': ['user__email', 'page'],
                'unique_together': {('user', 'page')},
            },
        ),
    ]
