# Generated by Django 5.1.5 on 2026-04-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_add_staff_page_permission'),
        ('product', '0049_add_order_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['approval_status'], name='vendor_approval_status_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_active'], name='vendor_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_featured'], name='vendor_is_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_marketplace'], name='vendor_is_marketplace_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['approval_status', 'is_active'], name='vendor_approval_active_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['category'], name='vendor_category_idx'),
        ),
    ]
