# Generated by Codex on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_vendor_perf_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpagepermission',
            name='page',
            field=models.CharField(
                choices=[
                    ('overview', 'Overview'),
                    ('orders', 'Order Management'),
                    ('vendor', 'Vendor Management'),
                    ('riders', 'Rider Management'),
                    ('rider-verification', 'Rider Verification'),
                    ('customer', 'Customer Management'),
                    ('insights', 'Insights'),
                    ('marketplace', 'Marketplace Management'),
                    ('transactions', 'Transactions'),
                    ('push-notifications', 'Push Notifications'),
                ],
                max_length=40,
            ),
        ),
    ]
