# Generated by Django 5.1.5 on 2026-05-30 08:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_staffmarketplaceassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='product_creation_grant_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of additional products this vendor may create while locked. Decremented by 1 on each successful product creation. When 0 and product_creation_locked is True, the vendor must contact support.'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='product_creation_locked',
            field=models.BooleanField(default=False, help_text="When True, this vendor cannot create new products without an admin-issued grant. Set automatically the first time the admin configures pricing for one of the vendor's products if the vendor's category has lock_products_after_approval enabled. Can be toggled manually by admins."),
        ),
        migrations.CreateModel(
            name='ProductCreationGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('grant', 'Grant'), ('reset', 'Reset to zero'), ('lock', 'Manually locked'), ('unlock', 'Manually unlocked')], default='grant', max_length=16)),
                ('count', models.PositiveIntegerField(default=0, help_text='Number of product creations granted by this action (0 for reset/lock/unlock).')),
                ('balance_after', models.PositiveIntegerField(default=0, help_text="Vendor's grant balance immediately after this action was applied.")),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_product_creation_grants', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_creation_grants', to='account.vendor')),
            ],
            options={
                'verbose_name': 'Product Creation Grant',
                'verbose_name_plural': 'Product Creation Grants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', '-created_at'], name='pcg_vendor_recent_idx')],
            },
        ),
    ]
