# Generated by Django 5.1.5 on 2025-02-14 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_profile_id_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the system category.', max_length=100)),
                ('description', models.TextField(help_text='A detailed description of the system category.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the category was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the category was last updated.')),
            ],
        ),
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the vendor category.', max_length=100)),
                ('description', models.TextField(help_text='A detailed description of the vendor category.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this vendor category is active or not.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the category was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the category was last updated.')),
                ('vendor', models.ForeignKey(help_text='The vendor associated with this category.', on_delete=django.db.models.deletion.CASCADE, to='account.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the product.', max_length=100)),
                ('description', models.TextField(help_text='A detailed description of the product.')),
                ('price', models.DecimalField(decimal_places=2, help_text='The regular price of the product.', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='An image of the product.', null=True, upload_to='products/')),
                ('stock', models.IntegerField(default=0, help_text='The number of units available in stock.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the product is active and available for sale.')),
                ('is_delete', models.BooleanField(default=False, help_text='Indicates whether the product is marked for deletion.')),
                ('is_featured', models.BooleanField(default=False, help_text='Indicates whether the product is marked for featured.')),
                ('apply_discount', models.BooleanField(default=False, help_text='Indicates whether a discount is applied to this product.')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='The discount percentage on this product (e.g., 20 for 20%).', max_digits=5, null=True)),
                ('discount_start_date', models.DateTimeField(blank=True, help_text='The start date of the discount.', null=True)),
                ('discount_end_date', models.DateTimeField(blank=True, help_text='The end date of the discount.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the product was last updated.')),
                ('vendor', models.ForeignKey(help_text='The vendor selling this product.', on_delete=django.db.models.deletion.CASCADE, to='account.vendor')),
                ('system_category', models.ForeignKey(help_text='The system category to which this product belongs.', on_delete=django.db.models.deletion.CASCADE, to='product.systemcategory')),
                ('category', models.ForeignKey(help_text='The vendor category of this product.', on_delete=django.db.models.deletion.CASCADE, to='product.vendorcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Timestamp when the product was added to the user's favorites.")),
                ('user', models.ForeignKey(help_text='The user who favorited the product.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='The product that is favorited.', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
