# Generated by Django 5.1.5 on 2025-04-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track_id',
            field=models.CharField(default=1, help_text='Unique tracking ID per user', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('canceled', 'Canceled'), ('delivered', 'Delivered')], default='pending', help_text='The current status of the order.', max_length=20),
        ),
    ]
