# Generated by Django 5.1.5 on 2025-04-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_order_track_id_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
