# Generated by Django 5.1.5 on 2025-02-15 21:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_favorite_updated_at_product_purchases_product_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Product image', upload_to='product_images')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product image was')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the product image was last')),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary image for the product')),
                ('is_active', models.BooleanField(default=True, help_text='Is this image active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
