# Generated by Django 5.1.5 on 2025-05-01 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rider_current_latitude_rider_current_longitude_and_more'),
        ('product', '0004_systemcategory_logo_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_delivery_time',
            field=models.DateTimeField(blank=True, help_text='Actual time when the order was delivered.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='actual_pickup_time',
            field=models.DateTimeField(blank=True, help_text='Actual time when the rider picked up the order.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, help_text='Estimated time when the order will be delivered.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_pickup_time',
            field=models.DateTimeField(blank=True, help_text='Estimated time when the rider will pick up the order.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, help_text='The rider assigned to deliver this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='account.rider'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('near_delivery', 'Near Delivery Location'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', help_text='The current status of the order.', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rider_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rider_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distance_to_delivery', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated distance to delivery in meters', max_digits=10, null=True)),
                ('estimated_time_remaining', models.IntegerField(blank=True, help_text='Estimated time remaining in minutes', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tracking', to='product.order')),
            ],
        ),
    ]
