# Generated by Django 5.1.5 on 2025-05-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order_actual_delivery_time_order_actual_pickup_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='starting_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='The starting delivery fee for this product.', max_digits=10),
        ),
    ]
