# Generated by Django 5.1.5 on 2025-06-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_starting_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('near_delivery', 'Near Delivery Location'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', help_text='The delivery status of the order.', max_length=20),
        ),
    ]
