# Generated by Django 5.1.5 on 2025-06-12 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If this product is a variant, this points to the main product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product'),
        ),
    ]
