# Generated by Django 5.1.5 on 2025-06-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
