# Generated by Django 5.1.5 on 2025-07-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_systemcategory_is_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcategory',
            name='name_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
