# Generated by Django 5.1.5 on 2025-07-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_order_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The delivery fee of the order.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="service_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The service fee of the order.",
                max_digits=10,
            ),
        ),
    ]
