# Generated by Django 5.1.5 on 2025-07-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_order_delivery_fee_order_service_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The discount amount of the order.",
                max_digits=10,
            ),
        ),
    ]
