# Generated by Django 5.1.5 on 2025-07-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_order_discount_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("wallet", "Wallet"), ("link", "Link")],
                default="wallet",
                help_text="The payment method of the order.",
                max_length=20,
            ),
        ),
    ]
