# Generated by Django 5.1.5 on 2025-07-29 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverytracking",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_delivery_trackings",
                to="product.order",
            ),
        ),
    ]
