# Generated by Django 5.1.5 on 2025-07-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0017_alter_deliverytracking_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
