# Generated by Django 5.1.5 on 2025-08-11 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0018_order_delivery_latitude_order_delivery_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="estimated_delivery_time",
        ),
        migrations.RemoveField(
            model_name="order",
            name="estimated_pickup_time",
        ),
        migrations.AddField(
            model_name="order",
            name="new_estimated_delivery_time",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(seconds=1800),
                help_text="Estimated time when the order will be delivered.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="new_estimated_pickup_time",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(seconds=1800),
                help_text="Estimated time when the rider will pick up the order.",
                null=True,
            ),
        ),
    ]
