# Generated by Django 5.1.5 on 2025-08-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0020_userfavoritevendor_delete_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "confirmed"),
                    ("awaiting_rider", "awaiting_rider"),
                    ("rider_assigned", "Rider Assigned"),
                    ("ready_for_pickup", "Ready for Pickup"),
                    ("picked_up", "Picked Up"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                help_text="The delivery status of the order.",
                max_length=20,
            ),
        ),
    ]
