# Generated by Django 5.1.5 on 2025-09-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0021_alter_order_delivery_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="select_at_least_one_variant_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
