# Generated by Django 5.1.5 on 2025-09-20 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0022_product_select_at_least_one_variant_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariantCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        help_text="The name of the product variant category.",
                        max_length=100,
                    ),
                ),
                (
                    "select_at_least_one_variant_enabled",
                    models.BooleanField(default=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the product variant category was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the product variant category was last updated.",
                    ),
                ),
                (
                    "child_products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The child products that belong to this variant category.",
                        related_name="variant_categories",
                        to="product.product",
                    ),
                ),
                (
                    "parent_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="The parent product to which this variant category belongs.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
