# Generated by Django 5.1.5 on 2025-09-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0023_productvariantcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("preparing", "Preparing"),
                    ("ready_for_pickup", "Ready for Pickup"),
                    ("picked_up", "Picked Up"),
                    ("in_transit", "In Transit"),
                    ("near_delivery", "Near Delivery Location"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="The current status of the order.",
                max_length=20,
            ),
        ),
    ]
