# Generated by Django 5.1.5 on 2025-09-25 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0022_rider_nin_back_rider_nin_front"),
        ("product", "0024_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclinedOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("declined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declined_by_riders",
                        to="product.order",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declined_orders",
                        to="account.rider",
                    ),
                ),
            ],
            options={
                "unique_together": {("rider", "order")},
            },
        ),
    ]
