# Generated by Django 5.1.5 on 2025-10-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0025_declinedorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="image",
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
