# Generated by Django 5.1.5 on 2025-11-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0028_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("preparing", "Preparing"),
                    ("looking_for_rider", "Looking for Rider"),
                    ("rider_assigned", "Rider Assigned"),
                    ("picked_up", "Picked Up"),
                    ("in_transit", "In Transit"),
                    ("near_delivery", "Near Delivery Location"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="The current status of the order.",
                max_length=20,
            ),
        ),
    ]
