# Generated by Django 5.1.5 on 2025-11-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0030_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="estimated_dropoff_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Estimated time when the order will be delivered to customer.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_pickup_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Estimated time when the rider will pick up the order.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_distance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total distance for delivery in kilometers.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
