# Generated by Django 5.1.5 on 2026-01-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0031_order_estimated_dropoff_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemcategory",
            name="is_special_pricing",
            field=models.BooleanField(
                default=False,
                help_text="Enable special delivery pricing (50% discount on additional items). E.g., Fine Bites, Oyibo",
            ),
        ),
    ]
