# Generated by Django 5.1.5 on 2026-01-09 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0032_systemcategory_is_special_pricing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="systemcategory",
            name="commission_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Custom commission rate for this category. Leave blank to use platform default.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Default platform commission percentage (e.g., 10.00 for 10%)",
                        max_digits=5,
                    ),
                ),
                (
                    "is_commission_active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable commission calculation platform-wide",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Settings",
                "verbose_name_plural": "Platform Settings",
            },
        ),
    ]
