# Generated by Django 5.1.5 on 2026-01-11 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0033_systemcategory_commission_percentage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the variant option, e.g., 'Rice'.",
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for this variant option.",
                        max_digits=10,
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, help_text="Stock for this variant option."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this variant option active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The variant category this option belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="product.productvariantcategory",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product this variant is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_variants",
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItemVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Quantity of this variant selected."
                    ),
                ),
                (
                    "price_at_purchase",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the variant at the time of order.",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        help_text="The order item this variant selection belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_selections",
                        to="product.orderitem",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        help_text="The selected variant option.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productvariant",
                    ),
                ),
            ],
        ),
    ]
