# Generated by Django 5.1.5 on 2026-01-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0034_productvariant_orderitemvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="delivery_percentage_off",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Global delivery discount (%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemcategory",
            name="delivery_percentage_off",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Delivery discount for this category (%)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
