# Generated by Django 5.1.5 on 2026-01-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0035_platformsettings_delivery_percentage_off_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariantcategory",
            name="allow_multiple_quantity",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether a user can select more than one quantity of the same variant.",
            ),
        ),
        migrations.AddField(
            model_name="productvariantcategory",
            name="allow_multiple_variant_selection",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether a user can select multiple different variants from this category.",
            ),
        ),
        migrations.AddField(
            model_name="productvariantcategory",
            name="max_quantity_per_option",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of different variants a user can select from this category each. Leave blank for no limit.",
                null=True,
            ),
        ),
    ]
