# Generated by Django 5.1.5 on 2026-01-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0036_productvariantcategory_allow_multiple_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariantcategory",
            old_name="max_quantity_per_option",
            new_name="max_quantity_per_variant",
        ),
        migrations.RemoveField(
            model_name="productvariantcategory",
            name="child_products",
        ),
    ]
