# Generated by Django 5.1.5 on 2026-03-12 18:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0038_alter_deliveryfee_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "boundary",
                    models.JSONField(
                        help_text="List of coordinates defining the zone boundary (Polygon)"
                    ),
                ),
                ("fixed_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="base_distance_range",
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=10),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="base_fare",
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="incremental_charge",
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="incremental_distance",
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="is_multi_stop_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="max_delivery_distance",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="platform_operational_fee",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.CreateModel(
            name="EstateGatePass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gate_fee_bike",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "gate_fee_bus",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.deliveryzone",
                    ),
                ),
            ],
        ),
    ]
