# Generated by Django 5.1.5 on 2026-03-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0039_deliveryzone_platformsettings_base_distance_range_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="rider_earning",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The amount the rider earns from this order.",
                max_digits=10,
            ),
        ),
    ]
