# Generated by Django 5.1.5 on 2026-03-13 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0040_order_rider_earning"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryzone",
            options={
                "ordering": ["name"],
                "verbose_name": "Delivery Zone",
                "verbose_name_plural": "Delivery Zones",
            },
        ),
        migrations.AlterModelOptions(
            name="estategatepass",
            options={
                "ordering": ["name"],
                "verbose_name": "Estate Gate Pass",
                "verbose_name_plural": "Estate Gate Passes",
            },
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="boundary",
            field=models.JSONField(
                help_text="List of coordinates defining the zone boundary (Polygon). Coordinates should be provided as [latitude, longitude]. Example: [[6.5244, 3.3792], [6.5245, 3.3800], [6.5250, 3.3798], [6.5244, 3.3792]]"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="fixed_fee",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Fixed delivery fee for this zone. Example: 1500.00",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether this delivery zone is currently active.",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="name",
            field=models.CharField(
                help_text="Name of the delivery zone. Example: 'Lekki Phase 1 Zone'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="estategatepass",
            name="gate_fee_bike",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Gate pass fee charged for bike deliveries. Example: 500.00",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="estategatepass",
            name="gate_fee_bus",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Gate pass fee charged for bus/van deliveries. Example: 1500.00",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="estategatepass",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether this estate gate pass is active.",
            ),
        ),
        migrations.AlterField(
            model_name="estategatepass",
            name="location_zone",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the delivery zone this estate belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estate_gates",
                to="product.deliveryzone",
            ),
        ),
        migrations.AlterField(
            model_name="estategatepass",
            name="name",
            field=models.CharField(
                help_text="Name of the estate or gate. Example: 'Banana Island Gate'",
                max_length=100,
            ),
        ),
    ]
