# Generated by Django 5.1.5 on 2026-03-18 16:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0041_rider_average_customer_rating_and_more"),
        ("product", "0041_alter_deliveryzone_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="original_delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The delivery fee before any promo/discount was applied.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="promo_discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount amount specifically from promo code.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The final delivery fee paid by the customer.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The total discount amount of the order (items + order level).",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="The promo code (e.g., SAVE20). Optional for automatic promos.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "promo_type",
                    models.CharField(
                        choices=[
                            ("free_delivery", "Free Delivery"),
                            ("discounted_delivery", "Discounted Delivery"),
                            ("fixed_amount", "Fixed Amount Discount"),
                            ("percentage", "Percentage Discount"),
                            ("referral", "Referral Promo"),
                            ("new_user", "New User Promo"),
                            ("automatic", "Automatic / Direct Price Discount"),
                        ],
                        default="fixed_amount",
                        max_length=30,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The discount value (amount or percentage)",
                        max_digits=10,
                    ),
                ),
                (
                    "min_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Minimum order value to apply this promo",
                        max_digits=10,
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount amount (for percentage promos)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "usage_limit_per_user",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many times a single user can use this code",
                    ),
                ),
                (
                    "total_usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total number of times this code can be used across all users",
                        null=True,
                    ),
                ),
                (
                    "max_distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum delivery distance for this promo",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_automatic",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this discount is applied automatically without a code",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicable_categories",
                    models.ManyToManyField(
                        blank=True, related_name="promos", to="product.systemcategory"
                    ),
                ),
                (
                    "applicable_customers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific users this promo is for",
                        related_name="targeted_promos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "applicable_vendors",
                    models.ManyToManyField(
                        blank=True, related_name="promos", to="account.vendor"
                    ),
                ),
                (
                    "applicable_zones",
                    models.ManyToManyField(
                        blank=True, related_name="promos", to="product.deliveryzone"
                    ),
                ),
            ],
            options={
                "db_table": "promo_codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="product.promocode",
            ),
        ),
        migrations.CreateModel(
            name="PromoUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount before discount",
                        max_digits=10,
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount after discount",
                        max_digits=10,
                    ),
                ),
                (
                    "distance_at_usage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_usages",
                        to="product.order",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="product.promocode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "promo_usages",
                "unique_together": {("promo", "order")},
            },
        ),
    ]
