# Generated by Django 5.1.5 on 2026-03-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0042_order_original_delivery_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryfee",
            name="original_amount",
            field=models.FloatField(default=0),
        ),
    ]
