# Generated by Django 5.1.5 on 2026-03-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0043_deliveryfee_original_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="is_new_user_promo",
            field=models.BooleanField(
                default=False,
                help_text="Whether this promo is automatically applied to new users' first orders",
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="referrer_reward_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("wallet_credit", "Wallet Credit"),
                    ("fixed_amount", "Fixed Amount Discount"),
                    ("percentage", "Percentage Discount"),
                    ("free_delivery", "Free Delivery"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="referrer_reward_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The value of the reward for the referrer",
                max_digits=10,
            ),
        ),
    ]
