# Generated by Django 5.1.5 on 2026-03-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0044_promocode_is_new_user_promo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="description",
            field=models.TextField(
                blank=True, help_text="A brief description of this promo", null=True
            ),
        ),
    ]
