# Generated by Django 5.1.5 on 2026-04-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0045_promocode_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="platform_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The amount that goes to the platform as commission.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vendor_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The amount that goes to the vendor after commission.",
                max_digits=10,
            ),
        ),
    ]
