# Generated by Django 5.1.5 on 2026-04-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_order_platform_amount_order_vendor_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('looking_for_rider', 'Looking for Rider'), ('rider_assigned', 'Rider Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('near_delivery', 'Near Delivery Location'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('payment_failed', 'Payment Failed')], default='pending', help_text='The current status of the order.', max_length=20),
        ),
    ]
