# Generated by Django 5.1.5 on 2026-05-05 23:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_add_order_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BukaItemServiceCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flat_charge', models.DecimalField(decimal_places=2, help_text="Fixed naira service charge added to this item's price per unit.", max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(help_text='The Buka product this service charge applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='buka_service_charge', to='product.product')),
            ],
            options={
                'verbose_name': 'Buka Item Service Charge',
                'verbose_name_plural': 'Buka Item Service Charges',
            },
        ),
        migrations.CreateModel(
            name='ServiceChargeTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_price', models.DecimalField(decimal_places=2, help_text='Lower bound of the product price range (inclusive). E.g. 100.00', max_digits=12)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Upper bound of the product price range (inclusive). Leave blank for open-ended top tier.', max_digits=12, null=True)),
                ('flat_charge', models.DecimalField(decimal_places=2, help_text='Fixed naira amount charged as a service fee for items in this range.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_category', models.ForeignKey(help_text='The system category this tier belongs to (e.g. Marketplace, Pharmacy).', on_delete=django.db.models.deletion.CASCADE, related_name='service_charge_tiers', to='product.systemcategory')),
            ],
            options={
                'verbose_name': 'Service Charge Tier',
                'verbose_name_plural': 'Service Charge Tiers',
                'ordering': ['system_category', 'min_price'],
            },
        ),
    ]
