# Generated by Codex on 2026-05-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_vendor_perf_indexes'),
        ('product', '0050_add_service_charge_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicechargetier',
            name='vendor',
            field=models.ForeignKey(
                blank=True,
                help_text='Optional vendor-specific tier. Leave blank to make this a category default.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='service_charge_tiers',
                to='account.vendor',
            ),
        ),
        migrations.AlterModelOptions(
            name='servicechargetier',
            options={
                'ordering': ['system_category', 'vendor__name', 'min_price'],
                'verbose_name': 'Service Charge Tier',
                'verbose_name_plural': 'Service Charge Tiers',
            },
        ),
    ]
