# Generated by Codex on 2026-05-07

import django.db.models.deletion
from django.db import migrations, models


def backfill_buka_charge_vendor(apps, schema_editor):
    BukaItemServiceCharge = apps.get_model('product', 'BukaItemServiceCharge')
    for charge in BukaItemServiceCharge.objects.select_related('product').all():
        if charge.product_id and not charge.vendor_id:
            charge.vendor_id = charge.product.vendor_id
            charge.save(update_fields=['vendor'])


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_vendor_perf_indexes'),
        ('product', '0051_servicechargetier_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukaitemservicecharge',
            name='vendor',
            field=models.ForeignKey(
                blank=True,
                help_text='The vendor whose product this item charge applies to.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='buka_item_service_charges',
                to='account.vendor',
            ),
        ),
        migrations.RunPython(backfill_buka_charge_vendor, migrations.RunPython.noop),
    ]
