# Generated by Django 5.1.5 on 2026-05-08 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_vendor_perf_indexes'),
        ('product', '0052_bukaitemservicecharge_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BukaVariantServiceCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flat_charge', models.DecimalField(decimal_places=2, help_text="Fixed naira service charge added to this variant's price per unit.", max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The parent Buka product for this variant charge.', on_delete=django.db.models.deletion.CASCADE, related_name='buka_variant_service_charges', to='product.product')),
                ('variant', models.OneToOneField(help_text='The Buka product variant this service charge applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='buka_service_charge', to='product.productvariant')),
                ('vendor', models.ForeignKey(blank=True, help_text='The vendor whose product variant this charge applies to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buka_variant_service_charges', to='account.vendor')),
            ],
            options={
                'verbose_name': 'Buka Variant Service Charge',
                'verbose_name_plural': 'Buka Variant Service Charges',
            },
        ),
    ]
