# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_productvariant_track_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='referrer_reward_type',
            field=models.CharField(
                choices=[
                    ('none', 'None'),
                    ('wallet_credit', 'Wallet Credit'),
                    ('fixed_amount', 'Fixed Amount Discount'),
                    ('percentage', 'Percentage Discount'),
                    ('free_delivery', 'Free Delivery'),
                    ('discounted_delivery', 'Discounted Delivery'),
                ],
                default='none',
                max_length=20,
            ),
        ),
    ]
