# Generated by Django 5.1.5 on 2026-05-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_order_pickup_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcategory',
            name='lock_products_after_approval',
            field=models.BooleanField(default=False, help_text='When True, vendors in this category are blocked from adding new products once the admin has configured pricing for at least one of their products. The vendor must contact support to request additional product-creation grants. Intended for categories like Eatery/Buka where admin sets prices and commissions.'),
        ),
    ]
