# Generated by Django 5.1.5 on 2026-08-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_order_platform_earnings_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryfee',
            name='service_fee',
            field=models.FloatField(default=0, help_text='Platform service-fee portion of `amount`. Carried through to the order so the rider can be paid the transport part only.'),
        ),
    ]
