# Generated by Django 5.1.5 on 2025-10-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Configuration key (e.g., 'base_fee_tier_1')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pricing", "Pricing"),
                            ("timing", "Timing"),
                            ("multipliers", "Multipliers"),
                            ("thresholds", "Thresholds"),
                            ("cache", "Cache Settings"),
                        ],
                        default="pricing",
                        max_length=20,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("float", "Float"),
                            ("int", "Integer"),
                            ("json", "JSON"),
                            ("bool", "Boolean"),
                            ("string", "String"),
                        ],
                        default="float",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Configuration value (JSON for complex types)"
                    ),
                ),
                ("default_value", models.TextField(help_text="Default fallback value")),
                (
                    "description",
                    models.TextField(
                        help_text="Description of what this configuration controls"
                    ),
                ),
                (
                    "min_value",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum allowed value (for numeric types)",
                        null=True,
                    ),
                ),
                (
                    "max_value",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum allowed value (for numeric types)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="User who last updated this config",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Configuration",
                "verbose_name_plural": "Delivery Configurations",
                "db_table": "delivery_configuration",
                "ordering": ["category", "key"],
            },
        ),
    ]
