# Generated by Django 5.1.5 on 2025-11-23 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Announcement title", max_length=255),
                ),
                ("message", models.TextField(help_text="Announcement message/content")),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("customer", "Customers"),
                            ("vendor", "Vendors"),
                            ("rider", "Riders"),
                        ],
                        default="all",
                        help_text="Target audience for this announcement",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Priority level of the announcement",
                        max_length=20,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional image URL",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional action/deep link URL",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "action_label",
                    models.CharField(
                        blank=True,
                        help_text="Label for action button",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="When the announcement becomes active"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the announcement expires (optional)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the announcement is currently active",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Whether the announcement is published"
                    ),
                ),
                (
                    "send_push_notification",
                    models.BooleanField(
                        default=False, help_text="Send push notification to users"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "view_count",
                    models.IntegerField(default=0, help_text="Number of times viewed"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Admin user who created this announcement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "db_table": "announcements",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_views",
                        to="admin_manager.announcement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "announcement_views",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["target_audience", "is_active", "is_published"],
                name="announcemen_target__ea5c52_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["start_date", "end_date"], name="announcemen_start_d_46de7e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="announcementview",
            unique_together={("announcement", "user")},
        ),
    ]
