# Generated by Django 5.1.5 on 2025-11-27 19:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="action_label",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="action_url",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="image_url",
        ),
        migrations.CreateModel(
            name="AnnouncementImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        help_text="Image URL for the announcement.", max_length=500
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="admin_manager.announcement",
                    ),
                ),
            ],
            options={
                "db_table": "announcement_images",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Link URL for the announcement.", max_length=500
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Label for the link/action button.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="admin_manager.announcement",
                    ),
                ),
            ],
            options={
                "db_table": "announcement_links",
                "ordering": ["added_at"],
            },
        ),
    ]
