# Generated by Django 5.1.5 on 2025-11-29 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_manager", "0002_remove_announcement_action_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcementimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                help_text="Upload image file for the announcement.",
                null=True,
                upload_to="announcement_images/",
            ),
        ),
        migrations.AlterField(
            model_name="announcementimage",
            name="announcement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="admin_manager.announcement",
            ),
        ),
        migrations.AlterField(
            model_name="announcementimage",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Image URL for the announcement (optional if file is uploaded).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcementlink",
            name="announcement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="link",
                to="admin_manager.announcement",
            ),
        ),
    ]
