# Generated by Django 5.1.5 on 2026-03-18 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_manager", "0003_announcementimage_image_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PopupAnnouncement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Popup title", max_length=255)),
                ("message", models.TextField(help_text="Popup message/content")),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        help_text="Upload image file for the popup.",
                        null=True,
                        upload_to="popup_images/",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Image URL for the popup (optional if file is uploaded).",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "action_label",
                    models.CharField(
                        blank=True,
                        help_text="Label for the action button (e.g., 'Start Saving Now')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL or Deep Link for the action button",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("customer", "Customers"),
                            ("vendor", "Vendors"),
                            ("rider", "Riders"),
                        ],
                        default="all",
                        help_text="Target audience for this popup",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="When the popup becomes active"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the popup expires (optional)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the popup is currently active"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Whether the popup is published"
                    ),
                ),
                (
                    "show_once_per_user",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to show this popup only once per user",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "view_count",
                    models.IntegerField(default=0, help_text="Number of times viewed"),
                ),
                (
                    "click_count",
                    models.IntegerField(
                        default=0, help_text="Number of times action button was clicked"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Admin user who created this popup",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_popups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Popup Announcement",
                "verbose_name_plural": "Popup Announcements",
                "db_table": "popup_announcements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PopupAnnouncementView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "popup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_views",
                        to="admin_manager.popupannouncement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popup_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "popup_announcement_views",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="popupannouncement",
            index=models.Index(
                fields=["target_audience", "is_active", "is_published"],
                name="popup_annou_target__f354d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="popupannouncement",
            index=models.Index(
                fields=["start_date", "end_date"], name="popup_annou_start_d_112b4e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="popupannouncementview",
            unique_together={("popup", "user")},
        ),
    ]
