# Generated by Django 5.1.5 on 2025-06-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
