# Generated by Django 5.1.5 on 2025-07-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallettransaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='reference_code',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
