# Generated by Django 5.1.5 on 2025-07-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_wallettransaction_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="external_reference",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="response_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
