# Generated by Django 5.1.5 on 2025-07-19 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0005_wallettransaction_external_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="wallet.wallet",
            ),
        ),
    ]
