# Generated by Django 5.1.5 on 2026-03-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0007_wallettransaction_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("purchase", "Purchase"),
                    ("earning", "Rider Earning"),
                ],
                max_length=10,
            ),
        ),
    ]
