# Generated by Django 5.1.5 on 2026-04-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0008_alter_wallettransaction_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
